# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 00:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_auto_20170828_2055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_Inscricao', models.DateField(max_length=10)),
                ('preco', models.FloatField()),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='eventos.Evento')),
                ('pessoa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inscrição', to='eventos.PessoaFisica')),
            ],
        ),
    ]
